// {
//     title:'', (don't include any special characters)
//     description:'', use \n for new line
//     url:'',
//     image:'',
//     startDate:'',
//     registerLastDate:'',
//     eventDate:'',
// }

type Event = {
    title: string,
    description: string,
    url: string,
    asp: number,
    status: boolean,
    image: string,
    startDate: string,
    Venue: string,
    registerLastDate: string,
    eventDate: string,
}

export const EVENTS = [
    {
        title: 'Wednesday Cafe with Shaheen Hyder',
        description: 'From an Ember to a Blaze: The Journey of a Thriving Startup! 🤑\nJoin us this Wednesday Cafe as Shaheen Hyder, co- founder of MakeMyPass(our very own Shaheen Ikka), shares his inspiring startup stories and the journey of building MakeMyPass!\n✷Don’t miss out! Register now ✷',
        url: '',
        asp: 0,
        status: false,
        image: '/event7.jpg',
        startDate: '',
        Venue: 'Google Meet',
        registerLastDate: '',
        eventDate: '15-01-2025',
    },
    {
        title: 'Smart India Hackathon 2024 prelims',
        description: 'SJCET-BOOTCAMP-IEDC is back with Smart India Hackathon 2024. You will be trying to solve the problems existing in our society and these problem statements are given by various stakeholders. You can also choose your own problems, which will be another category. All you need to do is find a solution and start building. And this year it gets more exciting. We are going to make it an 18hr non stop Hackathon, starting from 5 pm of 10th September to 11 am of 11th September.',
        url: '',
        asp: 0,
        status: false,
        image: '/event6.jpg',
        startDate: '',
        Venue: 'Offline',
        registerLastDate: '',
        eventDate: '10-09-2024',
    },
    {
        title: 'Design Week 24',
        description: 'Design your Future!\n* A full week of hands-on learning in using design tools such as Figma and Photoshop and applying it to graphic and UI/UX design.\n* Do you want to start or continue your design journey?\n* This design week will teach you the skills you need to succeed in graphic and UI/UX design.\n* You will learn how to use popular design tools such as Figma and Photoshop.\n* The workshop will be held from July 29th to Aug 2nd from 4:30 to 5:30 at Makerspace.\n* Sign up today!',
        url: '',
        asp: 1,
        status: false,
        image: '/event5.jpg',
        startDate: '',
        Venue: 'Startup Bootcamp SJCET',
        registerLastDate: '',
        eventDate: '29-07-2024',
    },
    {
        title: 'TOP 20 CODERS 24',
        description: 'Are you a tech enthusiast with a knack for problem-solving? We are inviting all aspiring techies to participate in the upcoming coding competition, a gateway to the ranking of TOP 20 CODERS of SJCET at 2024.\nStimulate creativity 🧠, foster innovation 💡, and drive change 🔥.\nSeize the opportunity to showcase your skills on April 2024, and be a driving force for change!\nCalling all SJCET students!\nJoin us on a thrilling journey of building, collaboration, and problem-solving. Together, we can turn your talents into exciting prizes!',
        url: '',
        asp: 0,
        status: false,
        image: '/event3.jpg',
        startDate: '',
        Venue: 'Virtual & In-person',
        registerLastDate: '',
        eventDate: '06-04-2024',
    },
    {
        title: 'Official call for IEDC EXECOM 24!',
        description: "Ever wondered what it takes to be an IEDC EXECOM member? ❓\nWell, here's your chance to find out because we're excited to announce the official call for EXECOM 24!\nChoose the position that suits you best 🔍\nWe're eagerly waiting for individuals with a passion to be part of our team 💯\nEnhance your skills, and don't worry if you're a fresher 👾\nPositions are open for SJCETians from the first to third years\nPS: Each step you take in this quest determines what\'s waiting for you at the other end 🌀",
        url: '',
        asp: 1,
        status: false,
        image: '/event2.jpg',
        startDate: '',
        Venue: 'G-Form',
        registerLastDate: '',
        eventDate: '25-01-2024',
    },
] satisfies Event[]