// {
//     title:'', (don't include any special characters)
//     description:'', use \n for new line
//     url:'',
//     image:'',
//     startDate:'',
//     registerLastDate:'',
//     eventDate:'',
// }

type Event = {
    title: string,
    description: string,
    url: string,
    asp: number,
    status: boolean,
    image: string,
    startDate: string,
    Venue: string,
    registerLastDate: string,
    eventDate: string,
}

export const EVENTS = [
    {
        title: 'Prayana - Alumni Entrepreneur Meetup',
        description: 'SJCET IEDC proudly celebrates it is 10-year journey with Prayana 2025 - an exclusive alumni entrepreneurs meet bringing together successful alumni founders, students, investors, and industry leaders for a day of learning, inspiration, and networking.\n ✨ Chief Guest – Mr.Anoop Ambika, CEO, Kerala Startup Mission (KSUM)',
        url: 'https://iedc.sjcet.in/prayana',
        asp: 0,
        status: true,
        image: '/PRAYANA2025.jpg',
        startDate: '',
        Venue: 'St. Francis Hall , SJCET Palai',
        registerLastDate: '18-08-2025',
        eventDate: '23-08-2025',
    },
    {
        title: 'Wednesday Cafe - 13.08.2025',
        description: '*Wednesday Cafe☕* is back! And this time, we are diving into the power of _Personal Branding_.✨  \n Join us on Wednesday cafe\n (13-08-2025), a leading series by *IEDC Bootcamp SJCET Palai*, for an insightful session with three inspiring speakers:\n - Blesson K Tomy : Design Thinker and Innovator\n - Tims Tittus : Cybersecurity Specialist and Polymath\n- Parvathy V Nair : Creative Technologist and Community Builder',
        url: '',
        asp: 0,
        status: false,
        image: '/WEDCAFE1308.jpg',
        startDate: '',
        Venue: 'SJCET Bootcamp',
        registerLastDate: '',
        eventDate: '13-08-2025',
    },
    {
        title: 'Build And Ship',
        description: '🚀BUILD AND SHIP- SJCET EDITION\n5 Days. 1 Idea. Infinite possibilities \nThis isn not your average hackathon, this is where ideas turn into reality.\nAs a part of Innovation Fest, SJCET IEDC Bootcamp is here with a 5 day program where concepts become creations. Turn your idea into real, working projects in just 5 days with the freedom to work at your own pace. Build after college hours, at home, or anywhere your creativity flows.',
        url: '',
        asp: 0,
        status: false,
        image: '/BUILDANDSHIP.jpg',
        startDate: '',
        Venue: 'SJCET Bootcamp',
        registerLastDate: '',
        eventDate: '05-08-2025',
    },
    {
        title: 'INSENDIUM 10.0',
        description: '*Got ideas in your brain?* ⚡\n Or just vibing, waiting for that one spark?\n *SJCET Startup BOOTCAMP – IEDC* presents\n*INSENDIUM 10.0* \n🔥 An ideation workshop _exclusively_ for 2nd year students. \n Just two days of throwing around cool ideas, having fun, and maybe \n unlocking your inner genius.',
        url: '',
        asp: 0,
        status: false,
        image: '/INSENDIUM10.0.jpg',
        startDate: '',
        Venue: 'SJCET Bootcamp',
        registerLastDate: '',
        eventDate: '04-08-2025',
    },
    {
        title: 'Techy Pedia',
        description: 'Techies of SJCET is having a meetup 🍃 \n Reg now : https://nexus.sjcetpalai.ac.in/techipedia/ \nJoin the Meetup\n- Date :  July 31, 2025 (Thursday)\n- Time :  4:45 pm\n- Venue :  Bootcamp SJCET\nFeel free to join if you love tech and chaya ☕',
        url: '',
        asp: 0,
        status: false,
        image: '/Techypedia.jpg',
        startDate: '',
        Venue: 'SJCET Bootcamp',
        registerLastDate: '',
        eventDate: '31-07-2025',
    },
    {
        title: 'Wednesday Cafe with Shaheen Hyder',
        description: 'From an Ember to a Blaze: The Journey of a Thriving Startup! 🤑\nJoin us this Wednesday Cafe as Shaheen Hyder, co- founder of MakeMyPass(our very own Shaheen Ikka), shares his inspiring startup stories and the journey of building MakeMyPass!\n✷Don’t miss out! Register now ✷',
        url: '',
        asp: 0,
        status: false,
        image: '/event7.jpg',
        startDate: '',
        Venue: 'Google Meet',
        registerLastDate: '',
        eventDate: '15-01-2025',
    },
    {
        title: 'Smart India Hackathon 2024 prelims',
        description: 'SJCET-BOOTCAMP-IEDC is back with Smart India Hackathon 2024. You will be trying to solve the problems existing in our society and these problem statements are given by various stakeholders. You can also choose your own problems, which will be another category. All you need to do is find a solution and start building. And this year it gets more exciting. We are going to make it an 18hr non stop Hackathon, starting from 5 pm of 10th September to 11 am of 11th September.',
        url: '',
        asp: 0,
        status: false,
        image: '/event6.jpg',
        startDate: '',
        Venue: 'Offline',
        registerLastDate: '',
        eventDate: '10-09-2024',
    },
    {
        title: 'Design Week 24',
        description: 'Design your Future!\n* A full week of hands-on learning in using design tools such as Figma and Photoshop and applying it to graphic and UI/UX design.\n* Do you want to start or continue your design journey?\n* This design week will teach you the skills you need to succeed in graphic and UI/UX design.\n* You will learn how to use popular design tools such as Figma and Photoshop.\n* The workshop will be held from July 29th to Aug 2nd from 4:30 to 5:30 at Makerspace.\n* Sign up today!',
        url: '',
        asp: 1,
        status: false,
        image: '/event5.jpg',
        startDate: '',
        Venue: 'Startup Bootcamp SJCET',
        registerLastDate: '',
        eventDate: '29-07-2024',
    },
    {
        title: 'TOP 20 CODERS 24',
        description: 'Are you a tech enthusiast with a knack for problem-solving? We are inviting all aspiring techies to participate in the upcoming coding competition, a gateway to the ranking of TOP 20 CODERS of SJCET at 2024.\nStimulate creativity 🧠, foster innovation 💡, and drive change 🔥.\nSeize the opportunity to showcase your skills on April 2024, and be a driving force for change!\nCalling all SJCET students!\nJoin us on a thrilling journey of building, collaboration, and problem-solving. Together, we can turn your talents into exciting prizes!',
        url: '',
        asp: 0,
        status: false,
        image: '/event3.jpg',
        startDate: '',
        Venue: 'Virtual & In-person',
        registerLastDate: '',
        eventDate: '06-04-2024',
    },
    {
        title: 'Official call for IEDC EXECOM 24!',
        description: "Ever wondered what it takes to be an IEDC EXECOM member? ❓\nWell, here's your chance to find out because we're excited to announce the official call for EXECOM 24!\nChoose the position that suits you best 🔍\nWe're eagerly waiting for individuals with a passion to be part of our team 💯\nEnhance your skills, and don't worry if you're a fresher 👾\nPositions are open for SJCETians from the first to third years\nPS: Each step you take in this quest determines what\'s waiting for you at the other end 🌀",
        url: '',
        asp: 1,
        status: false,
        image: '/event2.jpg',
        startDate: '',
        Venue: 'G-Form',
        registerLastDate: '',
        eventDate: '25-01-2024',
    },
] satisfies Event[]